services:
  app:
    image: arifbudianto/app:dashboard-be-dev-latest
    container_name: app
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app